Repository DeveloperAcademy-POSTECH/MC3-Team10-TenTen, pull requests merged in 2022-07, with the labels that each got.

#2 Chore/issue1 GitHub configs
  .github/ISSUE_TEMPLATE/base-issue-template.md
  .github/PULL_REQUEST_TEMPLATE/base-pr-template.md
Labels: Config

#16 [Chore] Realm Setup (#14)
  .github/workflows/CI_Dev.yml
  .gitignore
  OverTheRainbow/.swiftlint.yml
  OverTheRainbow/OverTheRainbow.xcodeproj/project.pbxproj
  OverTheRainbow/OverTheRainbow.xcworkspace/contents.xcworkspacedata
  OverTheRainbow/OverTheRainbow.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  OverTheRainbow/OverTheRainbow.xcworkspace/xcshareddata/xcschemes/OverTheRainbow.xcscheme
  OverTheRainbow/OverTheRainbow.xcworkspace/xcshareddata/xcschemes/OverTheRainbowTests.xcscheme
  OverTheRainbow/OverTheRainbow/DataAccess/DataAccessProvider.swift
  OverTheRainbow/OverTheRainbow/DataAccess/Error/RealmError.swift
  OverTheRainbow/OverTheRainbow/DataAccess/Realm/Dto/In/LetterInputDto.swift
  OverTheRainbow/OverTheRainbow/DataAccess/Realm/Dto/In/PetInputDto.swift
  OverTheRainbow/OverTheRainbow/DataAccess/Realm/Dto/Out/LetterResultDto.swift
  OverTheRainbow/OverTheRainbow/DataAccess/Realm/Dto/Out/PetResultDto.swift
  OverTheRainbow/OverTheRainbow/DataAccess/Realm/Model/Flower.swift
  OverTheRainbow/OverTheRainbow/DataAccess/Realm/Model/FlowerLog.swift
  OverTheRainbow/OverTheRainbow/DataAccess/Realm/Model/FlowerLogStatus.swift
  OverTheRainbow/OverTheRainbow/DataAccess/Realm/Model/Letter.swift
  OverTheRainbow/OverTheRainbow/DataAccess/Realm/Model/LetterStatus.swift
  OverTheRainbow/OverTheRainbow/DataAccess/Realm/Model/Pet.swift
  OverTheRainbow/OverTheRainbow/DataAccess/Realm/Model/RealmModel.swift
  OverTheRainbow/OverTheRainbow/DataAccess/Realm/Model/Words.swift
  OverTheRainbow/OverTheRainbow/DataAccess/Realm/RealmProvider.swift
  OverTheRainbow/OverTheRainbow/DataAccess/Realm/Repository/RealmRepository.swift
  OverTheRainbow/OverTheRainbow/DataAccess/Realm/Service/RealmService.swift
  OverTheRainbow/OverTheRainbow/Global/Util/DateConveter.swift
  OverTheRainbow/OverTheRainbow/Global/Util/UtilError.swift
  OverTheRainbow/OverTheRainbow/Network/TempFile.swift
  OverTheRainbow/OverTheRainbow/ViewController.swift
  OverTheRainbow/OverTheRainbowTests/DataAccess/Model/LetterStatusTest.swift
  OverTheRainbow/OverTheRainbowTests/DataAccess/Model/ModelTest.swift
  OverTheRainbow/OverTheRainbowTests/OverTheRainbowTests.swift
  OverTheRainbow/Podfile
  OverTheRainbow/Podfile.lock
Labels: Config

#31 [Feat] Realm API 개발
  OverTheRainbow/OverTheRainbow.xcodeproj/project.pbxproj
  OverTheRainbow/OverTheRainbow/DataAccess/DataAccessConfig.swift
  OverTheRainbow/OverTheRainbow/DataAccess/DataAccessProvider.swift
  OverTheRainbow/OverTheRainbow/DataAccess/DataAccessService.swift
  OverTheRainbow/OverTheRainbow/DataAccess/Error/RealmError.swift
  OverTheRainbow/OverTheRainbow/DataAccess/Realm/Dto/Out/FlowerResultDto.swift
  OverTheRainbow/OverTheRainbow/DataAccess/Realm/Dto/Out/HeavenViewResultDto.swift
  OverTheRainbow/OverTheRainbow/DataAccess/Realm/Dto/Out/MainViewResultDto.swift
  OverTheRainbow/OverTheRainbow/DataAccess/Realm/Dto/Out/WordResultDto.swift
  OverTheRainbow/OverTheRainbow/DataAccess/Realm/Extensions/Results.swift
  OverTheRainbow/OverTheRainbow/DataAccess/Realm/Model/FlowerLog.swift
  OverTheRainbow/OverTheRainbow/DataAccess/Realm/RealmConfig.swift
  OverTheRainbow/OverTheRainbow/DataAccess/Realm/Repository/RealmRepository.swift
  OverTheRainbow/OverTheRainbow/DataAccess/Realm/Service/RealmService.swift
  OverTheRainbow/OverTheRainbow/Global/Util/Date/DateConveter.swift
  OverTheRainbow/OverTheRainbow/Global/Util/Date/DateExtension.swift
  OverTheRainbow/OverTheRainbow/Global/Util/Date/DateFormat.swift
  OverTheRainbow/OverTheRainbowTests/DataAccess/Model/LetterStatusTest.swift
Labels: documentation, enhancement

#49 Feat/18 baseview
  OverTheRainbow/OverTheRainbow.xcodeproj/project.pbxproj
  OverTheRainbow/OverTheRainbow/AppDelegate.swift
  OverTheRainbow/OverTheRainbow/Base.lproj/LaunchScreen.storyboard
  OverTheRainbow/OverTheRainbow/Global/Extension/NSObject+Extension.swift
  OverTheRainbow/OverTheRainbow/Global/Extension/UICollectionView+Extension.swift
  OverTheRainbow/OverTheRainbow/Global/Literal/ImageLiterals.swift
  OverTheRainbow/OverTheRainbow/Global/UIComponent/BackButton.swift
  OverTheRainbow/OverTheRainbow/Info.plist
  OverTheRainbow/OverTheRainbow/Network/Model/LetterModel.swift
  OverTheRainbow/OverTheRainbow/SceneDelegate.swift
  OverTheRainbow/OverTheRainbow/Screens/Base/BaseViewController.swift
  OverTheRainbow/OverTheRainbow/Screens/LetterList/LetterListViewController.swift
  OverTheRainbow/OverTheRainbow/Screens/LetterList/UIComponent/LetterCollectionViewCell.swift
  OverTheRainbow/OverTheRainbow/Screens/letterList/LetterListViewController.swift
  OverTheRainbow/Podfile
  OverTheRainbow/Podfile.lock
Labels: enhancement

#65 Feat/43 file manager
  OverTheRainbow/OverTheRainbow.xcodeproj/project.pbxproj
  OverTheRainbow/OverTheRainbow/DataAccess/DataAccessService.swift
  OverTheRainbow/OverTheRainbow/DataAccess/Error/ImageManagerError.swift
  OverTheRainbow/OverTheRainbow/DataAccess/ImageManager/ImageManager.swift
  OverTheRainbow/OverTheRainbow/DataAccess/ImageManager/ImageType.swift
  OverTheRainbow/OverTheRainbow/DataAccess/Realm/Dto/In/LetterInputDto.swift
  OverTheRainbow/OverTheRainbow/DataAccess/Realm/Dto/In/PetInputDto.swift
  OverTheRainbow/OverTheRainbow/DataAccess/Realm/Repository/RealmRepository.swift
  OverTheRainbow/OverTheRainbow/DataAccess/Realm/Service/RealmService.swift
  OverTheRainbow/OverTheRainbow/Global/Util/Date/DateFormat.swift
Labels: enhancement
